### ISSUE TITLE
Notifications: new Aspect, new comment on Aspect

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/notifications#107]
## Description

As a community member I want to know what is happening
As a community manager I want to have people coming back to the hub + challenge

## Acceptance criteria

- [x] New notification event: aspect created
- [x] New notification event: comment on Aspect I've created
- [x] Two New email templates per notification event
- [x] New user preferences in notifications-community-administrator group
- [x] New user preferences in notifications group
- [x] User preference for member
 - Notify on comment created on Aspect I've created
- [x] User preference for admin: 
 - Notify on created aspect in a community
 - Notify on created comment on aspect
- [ ] Automated tests covering the functionality

**Comment by Comoque1** [comment]
Made exploratory testing on ACC end looks OK.
Will add the api tests as part of a separate [issue](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/test-suites/120)
