### ISSUE TITLE
Notifications-lib package for DTOs + commands

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/notifications#115]
## Description
As a developer I want to have a maintainable way of managing the interactions between the microservices in usage in the platform

## Acceptance criteria
- [ ] Make notifications repo to have two packages: notifications-lib, notifications-service (monorepo)
- [ ] **notifications-lib**:  has DTO definitions for all the incoming and outgoing payloads, as well as enum for message types supported. This package to be published as "@alkemio/notifications-lib" in NPM.
- [ ] **notifications-service**: has what is the actual service (builds to a docker image), and then uses the notifications-libpackage
- [ ] **server**: updated to alkemio/notifications-lib package, replacing the current notificationes.event.type enum and notifications service payload definitions. 
- [ ] Update the build pipelines to reflect the new code structure

**Comment by hero101** [comment]
- The suggested 'client' is not a client at all IMO - it's a library of types that have to be used for input/output operations.
