### ISSUE TITLE
Links to content in email notifications

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/notifications#143]
## Description

As a User I want to directly be able to access the content that is mentioned in the email instead of only a link to the Hub/Challenge/Opportunity dashboard (e.g. directly to the dialog of a new aspect, new callout, new comment on my aspect)

## Acceptance criteria
- [ ] Update the relevant event payloads to include sufficient information to be able to generate the URLs for the following event types: CALLOUT PUBLISHED, CARD CREATED, CANVAS CREATED, COMMENT ADDED TO CARD, COMMENT ADDED TO DISCUSSION CALLOUT (names are approximate!)
- [ ] Add urls to email template payloads for above types for accessing the content
- [ ] Per notification type add in some relevant text 
- CARD ADDED: share the title and the first 5 words of the description..
- COMMENT: show the comment text
...

Note: this card can focus on showing the technical path, the exact email contents to be worked by product after the data flow is working. 

## Additional Context
Try to add as much additional info for product to work with.

**Comment by hero101** [comment]
I don't believe a technical path needs to be worked on here, everything is shared through a payload between two services from the start.
On the contrary, what is shared (in the payload between services) is heavily influenced by the content of that emails.
