### ISSUE TITLE
BUG: When user create a Card, members receive notifications for Card and Aspect

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/notifications#144]
**Describe the bug**

**To Reproduce**

1. Go to a Hub / Explore page
2. Authenticate on different browsers with different Users, GA, HA and HM
3. GA creates a card on a callout - 5 notifications are sent.
 - 2 of the messages have title: [test] New **Card** created by admin
 - 3 of the messages have title: test - New **aspect** created by admin, have a look!
 - The GA and HA receive the mails twice.
 - The link within the message body is in quotes 
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/15763701-d75b-42b7-b9cd-bd11bc3b8486)

**Expected behavior**
TBD

**Comment by techsmyth** [comment]
Quotes is fine, but it looks like test appears twice?

**Comment by Comoque1** [comment]
The word 'test' appears twice, as the name of the hub and the name of the aspect is 'test'. Will try to avoid this in the future description.
