### ISSUE TITLE
Notification for comment on discussions callout

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/notifications#150]
## Description

As a   user I want to be notified when a new comment is added to a callout 

## Acceptance criteria

- [ ] New preference to allow users to receive notifications when a comment is added to a discussion Callout. Default is true, in both migration to add it and in new user profiles. 
- [ ] New notification event to trigger the notification from notification service
- [ ] New notification email template for comment added on callout
- [ ] Migration for new preference

**Comment by hero101** [comment]
- I don't think it's useful for every user of a community to receive every comment on every discussion Callout

**Comment by Flor-e** [comment]
> * I don't think it's useful for every user of a community to receive every comment on every discussion Callout

I agree with the above. Would be better to be able to follow a specific callout if you are interested in it. And on top of that: be able to see direct replies on your comments (but that would first require a reply function).
