### ISSUE TITLE
Global hub admins to receive new user sign up notifications 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/notifications#151]
## Description

As a global hub admin I want to be able to receive notifications for new users signing up

## Acceptance criteria

- [ ] Extend configuration in Notifications repo so that global hub admins to receive notifications for new users signing up 
- [ ] Ensure global hub admins on the client see the related preference on their notification preferences page

## Additional Context
Client notification preference:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/68ef70e7-a643-4727-a9f9-5dcd07a1a15f)

**Comment by hero101** [comment]
I am confused - there is already an existing notification configured for global admins and global community admins, and an existing preference
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/52b8059f-fb23-4369-8578-3347ff476917)
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/d1ae58f3-641f-497e-a7be-b291a328ecae)
