### ISSUE TITLE
Notification on Canvas created

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/notifications#156]
## Description

As a   user I want to be notified when a new canvas is crated

## Acceptance criteria

- [ ] New preference to allow users to receive notifications when a canvas is added to a Canvas Callout. Default is true, in both migration to add it and in new user profiles. 
- [ ] New notification event to trigger the notification from notification service
- [ ] New notification email template for canvas added on callout
- [ ] Migration for new preference

## Additional Context

From previous issue:

- [ ] Notification email for both members and admins when a new canvas is created
- [ ] Following admins receive the notification (same as aspect_created notification)
   - [ ] HUB_ADMIN
   - [ ] CHALLENGE_ADMIN
   - [ ] OPPORTUNITY_ADMIN
- [ ] Following members receive the notification (same as aspect_created notification)
   - [ ] HUB_MEMBER
   - [ ] CHALLENGE_MEMBER
   - [ ] OPPORTUNITY_MEMBER
- [ ] Preference Set - see additional context
- [ ] Text same as aspect (src/templates/aspect.created.admin.js + src/templates/aspect.created.member.js) just change aspect with canvas 

## Additional Context
```typescript
      {
        definitionSet: 'user',
        group: 'NotificationCommunityAdmin',
        displayName: '[Admin] New canvas created',
        description:
          'Receive a notification when a canvas is created in a community I am an administrator of',
        valueType: 'boolean',
        type: UserPreferenceType.NOTIFICATION_CANVAS_CREATED_ADMIN,
      },
      {
        definitionSet: 'user',
        group: 'Notification',
        displayName: 'New canvas created',
        description:
          'Receive a notification when a canvas is created in a community I am a member of',
        valueType: 'boolean',
        type: UserPreferenceType.NOTIFICATION_CANVAS_CREATED,
      },
```

**Comment by Comoque1** [comment]
Newly registered user has the new preferences set to `false`
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ce066473-5a17-4954-b212-4c9f5eeaaefe)

```
SELECT pd.groupName, pd.displayName, pr.value, pd.definitionSet, us.displayName
FROM alkemio.preference_definition as pd
join alkemio.preference as pr on
(pd.id = preferenceDefinitionId)
join alkemio.user as us on	
(us.preferenceSetId = pr.preferenceSetId)
where  pd.displayName in ('New Canvas created', '[Admin] User profile deleted', 'New comment on Discssion')
```

**Comment by techsmyth** [comment]
@Comoque1 good catch. Now new users should have the notification for canvas created set to true; the other two remain false.
