### ISSUE TITLE
BUG: Links from messages notification are not clickable for Outlook and Yahoo clients

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/notifications#187]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/release-10-02-23-hub/dashboard
2. Share a link to Alkemio user that you have access on Yahoo / Outlook client - the links are shown as strings instead of links
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/2ada64d5-9880-4935-b3c6-10d8af58c22b)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/edc7eb8c-547c-4459-8475-d3364ad16eb3)

For gmail client is fine:
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/cbe320dd-513a-44d6-a17a-a41f1b79d997)

**Expected behavior**
URLs are dis[played as links.

**Comment by techsmyth** [comment]
@Comoque1 is this still the case with the updated notification contents?

**Comment by Comoque1** [comment]
Yes, now even for some of the mails received in gmail client, there are no links
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/254e6df6-4844-4298-8aaa-b1dda2a7648a)

**Comment by techsmyth** [comment]
The user at the bottom has never been a link, but we should indeed update it. I will look later at it...

**Comment by techsmyth** [comment]
@alstojanovic @Comoque1 please also check if this issue is better with the new templates...

**Comment by Comoque1** [comment]
Looks better with new templates.

Still have the issue with messages new lines on outlook, but links are loading.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/1f4af24b-95a6-4df5-a6b0-6955efcb9c38)

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/6501bcdd-b4a8-4e31-bd17-181c2d2c9396)
