### ISSUE TITLE
Notification for tagging in comment on Forum Discussion

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/notifications#198]
## Description

As a user I want to be notified if I am tagged in a comment on the Forum

## Acceptance criteria

- [ ] Notification for tagging / notification for tagging extended to also include mentions for tagging a user or organization in a comment on a Discussion.
- [ ] Email body must have a link to the forum discussion

Note: to use the same UserPreference for determining whether to send

TBD: re-use the existing Notification with email body based on values

Note: text for email just make a first go and we will refine.

**Comment by Comoque1** [comment]
Tested locally, for user works fine. For organization raised a bug: BUG: Mention organization is not possible from client #3903.
