### ISSUE TITLE
BUG: Notification email footer content not displaying 

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/notifications#213]
**Describe the bug**
The contents of email notifications is showing up very poorly:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/ed9ca131-c84a-4518-b233-f737b37b167d)

**To Reproduce**

1. Send a message to a user on production
2. Look at the copy email that was sent to you

**Expected behavior**
Email contents, including new lines and images in footers, are displaying nicely

**Comment by techsmyth** [comment]
@Comoque1 please investigate - this seems to be affecting every notification that I am receiving, so all users.

**Comment by Comoque1** [comment]
The issue comes from Outlook client.
The message is looking nicely formatted on gmail client..
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/c454815c-bbaf-4aad-a5e6-561ec57d1777)

**Comment by SimoneZaza** [comment]
@techsmyth This was one of the reasons we created the new templates. Images are often blocked by Outlook and some other email clients.

**Comment by SimoneZaza** [comment]
This is the template we created a while back. Without touching the contents, we could change the header to be the Alkemio icon + the word Alkemio in text (montserrat, bold, 25). The footer is -I think- also quite straigthforward with a horizontal line and some text with links, the same as on the Alkemio homepage. https://www.figma.com/file/YtaAcCasSx9FoYSH5lTve3/Alkemio-User-2-User-Emails?type=design&node-id=3%3A9&t=XE0HsC4nQ9T6EJkl-1
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/db6e5530-eba4-4f55-b603-757dc9f72118)
