### ISSUE TITLE
Notification for when an external user is invited

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/notifications#223]
## Description

As a potential new user on Alkemio I want to receive an email with the message from the user inviting me

## Acceptance criteria

- [ ] New invitation that is sent to external users based on the email address, name + message provided as part of the invitation
- [ ] Person doing the invitation to receive also a notification

**Comment by alstojanovic** [comment]
@techsmyth to be able to send a notification to an external email this requires modifying the notifications service to be able to build a recipients list without using a roles/credentials based user filtering system.

**Comment by valentinyanakiev** [comment]
Tested locally and worked fine for me with the latest changes.
