### ISSUE TITLE
BUG: Applicant is suggested to check status of application on its profile, but there it is not visible

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/notifications#241]
**Describe the bug**

**To Reproduce**

1. Go to go to ACC
2. Create an application to a community
3. Check the email
4. It has a message: Please view the status of your application on your profile., where 'profile' is link to the user profile, but we don't display the pending applications and in near future, this block will be removed.

![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e5396f0d-786b-4e4c-887b-c0e2e3c34c19)
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/869e23ec-02a9-490c-8677-37e628406e94)

**Expected behavior**
TBD

**Comment by alstojanovic** [comment]
This is obsolete since we removed this section from the profile.

**Comment by Comoque1** [comment]
@alstojanovic, agree, this issue is not valid anymore.
