### ISSUE TITLE
BUG: Outlook doesn't render correctly messages that have multiple lines of text

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/notifications#250]
**Describe the bug**

**To Reproduce**

1. Go to ACC env
2. Send direct message to a user with the following text:
```
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```
3. Check the message in outlook - all lines are displayed in same row.
Left is outlook, right gmail
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/db625f83-c51c-4dd5-8e0b-96951b54b0ed)

**Expected behavior**
New lines are shown correctly for outlook.

## Additional Context
Below is how the email is showing up on outlook.
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/49b

Timebox: 2 people to look at this together for 1.5h

**Comment by techsmyth** [comment]
@ccanos can you please do a bit of investigation to see what is feasible on this?

**Comment by SimoneZaza** [comment]
@techsmyth for me, this can move to UX6, but if I remember correctly you were keen on fixing this asap?

**Comment by SimoneZaza** [comment]
I've asked my personal assistent for some help on this one 😉:

Sure, I can help you with that. There are different ways to convert plain text to HTML using JavaScript, but one of the simplest and safest methods is to use the built-in DOMParser class and call the parseFromString() method. This will create a new HTML document from your plain text and escape any special characters that might cause formatting issues in Outlook. For example, you can use this function to convert your plain text to HTML:

JavaScript

function convertPlainTextToHTML(plainText) {
  // Create a new DOMParser instance
  var parser = new DOMParser();
  // Parse the plain text as HTML
  var htmlDoc = parser.parseFromString(plainText, "text/html");
  // Return the HTML body content as a string
  return htmlDoc.body.innerHTML;
}
AI-generated code. Review and use carefully. More info on FAQ.
Then, you can use this function to convert the user’s input from the input field on your website and assign it to the email body. For example:

JavaScript

// Get the user's input from the input field
var userInput = document.getElementById("inputField").value;
// Convert the user's input to HTML
var emailBody = convertPlainTextToHTML(userInput);
// Assign the email body to the email object
email.body = emailBody;
AI-generated code. Review and use carefully. More info on FAQ.
This way, your email will display the line breaks and other formatting correctly in Outlook. I hope this helps you solve your problem. If you have any other questions, please let me know. 😊

**Comment by Comoque1** [comment]
Looks better now:
<img width="1531" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekZ0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77a1fb88f0b881ecc2a728039774359ca89ee651/image.png" alt="image.png" />
