### ISSUE TITLE
BUG: I receive a notification as an admin while I'm not 

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/notifications#257]
**Describe the bug**
I'm an admin of a Space in which Challenges were created by others. To be exact, I'm an admin of the Building Alkemio Space, and Neil created a Challenge there called "Raising the Alkemio Profile". I didn't see it yet, and didn't do anything with it. Also in the Challenge settings I can see that I'm not a member, lead, or admin. However, I did receive the following email notification, stating that I'm an admin here:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckVYIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9c1509ccafcdf946f440feaeced1be3412625de3/image.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alstojanovic** [comment]
@SimoneZaza This issue happens also for 3 other notifications. I added a fix for them as well. New whiteboard created, new community member and new community application.

**Comment by Comoque1** [comment]
@techsmyth, @SimoneZaza, is it expected, in the above scenario, the Space admin not to receive a notification, if he create a post on Challenge level (without being a member) ?

**Comment by Comoque1** [comment]
The implementation is working as defined in the comments and description.
Updated the notifications tests, and ones approved, the story can be closed.
