### ISSUE TITLE
Do not send a notification to the person that send a comment

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/notifications#258]
## Description

As a user I only want to see notifications for messages posted by other users, I know I posted something!

## Acceptance criteria

- [ ] When a user posts a comment, do not send a notification to that user that a comment was added

## Additional Context
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGdZIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3ef7f69d7e777de398f2b91effe53c038a2689f3/image.png)

**Comment by Comoque1** [comment]
@SimoneZaza @techsmyth  this is one is hit by an end user and probably is time to start prioritizing. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGJYQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4bd11bac7a6329ba906a3986748bce896a2acb4b/image.png)

**Comment by techsmyth** [comment]
@Comoque1 good point, it is irritating...
