### ISSUE TITLE
BUG: community.displayName not resolving

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/notifications#264]
**Describe the bug**
The following email does not have the information about the user properly set:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcXZ6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b25b309e6cda9bbf9f3d783eee5dffb29ddc6a20/image.png)

**Expected behavior**
The community name should be used

**Comment by techsmyth** [comment]
@alstojanovic can you please have a look at this one? I am assuming it is a trivial one, but looks poor.

**Comment by Comoque1** [comment]
@techsmyth, this looks like an issue, but actually it is not.
Just double checked on ACC env works OK:
 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdG56IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--132e532c0d2bbbc5d0d6bc639db78c4b6e7dc3a1/image.png)

The reason for the example in the bug, is that the display name of the challenge is : `community.displayName`
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdHJ6IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0b4e0a7cd6b750ab7d3104ab1a868a4f8d5d45ea/image.png)


I suggest we close the issue.

**Comment by alstojanovic** [comment]
There still may be a bug on the client.

**Comment by alstojanovic** [comment]
@techsmyth can you please share on which env was this and which challenge?

**Comment by techsmyth** [comment]
ah ok, can be closed then!
