### ISSUE TITLE
BUG: When a user applies to a space and is accepted by the admin, notifications are triggered as if the admin joined instead

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/notifications#268]
**Describe the bug**
When the application of a user to a private space is accepted, the wrong user gets the notification: the admin instead of the person who joined. In this case, Merijn applied and Simone accepted. Simone received the following mails:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0V6QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0fdf91863e62421bb3b7740daa3e93d53fc52704/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd016QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a35d6b24dc67193b686326eba61195c2f1e16a9d/image.png)

**To Reproduce**

**Expected behavior**
Merijn to receive these emails

**Comment by Comoque1** [comment]
Tested on sandbox.
None user receive notification
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK05ZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a66b20318a0391d513bb28dc294fbc3305fcac35/image.png" alt="image.png" />

**Comment by Comoque1** [comment]
There was a preference that needs to be enabled.
After doing so, correct messages are sent to correct users.
