### ISSUE TITLE
Update new users email (invite to Welcome Space and other improvements)

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/notifications#273]
## Description

As a new user on the platform, I want to know where I can see/do/learn more about Alkemio.

## Acceptance criteria

- [ ] Nice and inviting text about Alkemio, what a user can do
- [ ] Include link to Welcome Space

**Comment by Comoque1** [comment]
Two of the links are point to wrong locations.
See screenshot
<img width="936" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMG1NQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e5ab0255797a77301902d6133342df95031e6fa/image.png" alt="image.png" />

**Comment by alstojanovic** [comment]
I think you haven't tested with the latest branch.
<img width="358" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1dNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d6185f264a17c9115e5edc9f9999fc76ce0236ba/image.png" alt="image.png" />
