### ISSUE TITLE
Change notification for creation of Whiteboard RT

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/notifications#282]
## Description

When all whiteboards are RT, we should remove the "RT" from our communications with users

## Acceptance criteria

Remove "-real-time" in the notifications:

<img width="1071" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkUvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ef4dbd02ba67d369f79a900598f747b0b5c43642/image.png" alt="image.png" />

**Comment by SimoneZaza** [comment]
I can't find this specific notification between the notification files. Maybe it was already removed by someone else?
<img width="846" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmhtQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f6e43de16a81c5442cc3f28ae143261fba22f6b/image.png" alt="image.png" />

**Comment by alstojanovic** [comment]
This notification falls under the callout.published.member. It's a generic one that uses {{callout.type}} to set the type of callout being published.
This will be resolved on it's own after the server code cleanup is done.
