### ISSUE TITLE
BUG: Email is "not accessible" for notifications@alkem.io user when a new user signs up

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/notifications#283]
**Describe the bug**
When a new user registers the platform, notification email is sent to GA, GSA, when they have the preference enabled.
The email should contain the registered user email.
Sometimes it is displayed as 'not accessible'

**To Reproduce**

1. no clear steps to reproduce

**Expected behavior**
Registered user email is visible.

<img width="1349" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDFOQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eab104c5c010f22257766c48a6939786b6ebe0e8/image.png" alt="image.png" />

## Additional context
Strongly suspect this is a race condition, whereby the notifications are triggered before the authorization policy is propagated on new user creation.

**Comment by techsmyth** [comment]
@hero101 I had a look at this one - and my suspicion is that this is due to the data loader cache of the authorization on the user entity. How do we ensure that the data loader cache for an authorization policy is reset once we have applied an authorization policy reset on a User?

**Comment by hero101** [comment]
> @hero101 I had a look at this one - and my suspicion is that this is due to the data loader cache of the authorization on the user entity. How do we ensure that the data loader cache for an authorization policy is reset once we have applied an authorization policy reset on a User?

@techsmyth There is no real data loader cache persisted for more than the timeframe of the request. We can have a short chat about it.
