### ISSUE TITLE
BUG: The profile link on registration email points to localhost

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/notifications#289]
**Describe the bug**

**To Reproduce**

1. Go to Register new account on Alkemio application
2. Check the Welcome email - the profile links are pointing to localhost, instead to the domain of the particular environment
<img width="944" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2lNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--13329bf3efa508bacb40a21ee7e446e31b54c7ae/image.png" alt="image.png" />

**Expected behavior**
Correct domain is used in user profile registration template.

**Comment by alstojanovic** [comment]
I cannot add a production label but this is a production issue.
