### ISSUE TITLE
BUG: Email not correctly wrapping on certain clients?

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/notifications#310]
**Describe the bug**
When going through the signup flow with a user on mac, the signup email didn't wrap in his email client. 

**To Reproduce**

1. Go through sign up flow on mac, check emails
2. Check in temp mail

**Expected behavior**
Email content to fit in the screen

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Areas that will be affected**
_Optional, to be added by developer if relevant_

**Comment by SimoneZaza** [comment]
@jeroentskui, can you check this and take relevant screenshots?

**Comment by jeroentskui** [comment]
[](url)

![Image](https://github.com/alkem-io/notifications/assets/26659857/1ca53123-9ba7-4f25-a386-736e58c6c6b3)

**Comment by jeroentskui** [comment]
mail, thudnerbolt; etc.. mac has a number of email clients; (none of which i use haha) i can set some up to replicate this but maybe we have a mac user who does use email clients @keyboardguy25 or @StefanAlkemio

**Comment by keyboardguy25** [comment]
@jeroentskui I also don't use any of those clients 🤔

**Comment by jeroentskui** [comment]
yeah i tried with the default mail client on mac and i had no problems signing up either; 

![Image](https://github.com/alkem-io/notifications/assets/26659857/f1e22a23-d751-4e43-8a45-afa6e62b6fb3)

so im unable to recreate this bug :S

**Comment by jeroentskui** [comment]
![Image](https://github.com/alkem-io/notifications/assets/26659857/9c6a6256-86dd-43e6-991b-b44888c8e8dc)
