### ISSUE TITLE
Notifications: New member joining to be applicable to all contributor types

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/notifications#328]
## Description

As a space admin I want to know when there is a new member, regardless of contributor type

## Acceptance criteria
- [ ] Update the CommunityNewMember to be applicable to all contributor types i.e. User, VC + Organization. The contributor type to be clearly displayed in the email text. The link should be as with the current user notification. 
## Additional Context
https://www.figma.com/design/oKRFyc7P9WwlNyIWAiiHKf/Inviting?node-id=68-3&t=FMEAi1gdenS9hEn9-1

## Areas that will be affected 
 
_To be added during the refinement_

**Comment by valentinyanakiev** [comment]
@techsmyth this was linked to unrelated item
