### ISSUE TITLE
BUG: User who joins community don't receive a notification

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/notifications#333]
**Describe the bug**

**To Reproduce**

1. Trigger the following tests: `npm run test:notifications ./test/functional-api/notifications/community/notifications-join-community.it-spec.ts` 
<img width="1710" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWFnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--420f375cb83ff9ac944550b4acc1356e11e67497/image.png" alt="image.png" />

2. Or
3. Enable user preference: `Receiver notification when I join a community` from user profile settings / notifications
4. Join a community - notification is not received

**Expected behavior**
If joiner has preference enabled, he must receive notification.

**Comment by techsmyth** [comment]
Worse is that it sent my local notifications into an infinite loop ==> crashed the service:
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkNnQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd07398588b053b61dbac3d7094d35a98523a8ac/image.png" alt="image.png" />

**Comment by valentinyanakiev** [comment]
retested, still applicable

**Comment by techsmyth** [comment]
Did you release a new version of the notifications service?
