### ISSUE TITLE
In-app notifications only for Beta testers

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/notifications#357]
## Description

As a Product owner
I want to roll out the in-app notifications only to Beta users
So that I can have feedback only from the specific target group

## Acceptance criteria

- [ ] The incoming in-app notifications from the notifications microservice are to be stored only for Users with the `BETA_TESTER` credential 
- [ ] The notification icon on the client is visible only for Users with the `BETA_TESTER` credential
- [ ] Queries on the client are executed only for Users with the `BETA_TESTER` credential

**Comment by hero101** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Alkemio-Development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/notifications/357?planning-poker) with Zenhub @bobbykolev

**Comment by bobbykolev** [comment]
The client work was done as part of: 
https://github.com/alkem-io/client-web/issues/7211

**Comment by Comoque1** [comment]
Tested OK on DEV env.
A couple of stories and bugs that are remained are linked to the [epic](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/alkemio/419)
