### ISSUE TITLE
BUG: Notifications are sent on every second application

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/notifications#40]
**Describe the bug**
Notifications are sent on every second application.

**To Reproduce**

1. Go to https://dev.alkem.io/ioio/apply
2. Fill the required field and press apply - no notifications are send (no errors in the console)
3. Navigate to another ecoverse and click "apply" - notifications are sent correctly

**Expected behavior**
Every application must send notifications (if applicable).

**Comment by valentinyanakiev** [comment]
![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/720760c8-a33f-44ff-8f44-5fafdb803824)

**Comment by valentinyanakiev** [comment]
Created 3 applications and worked just fine for me.

**Comment by Comoque1** [comment]
Tested OK on DEV env.
