### ISSUE TITLE
BUG: Events should not be consumed if notifications cannot be sent

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/notifications#45]
**Describe the bug**
If the notifications service is not able to send emails, then the events should not be consumed

**To Reproduce**
Setup the notification service so that it cannot connect to the server
Start it up
Trigger an applicaiton created event
The event is consumed even though no emails are sent

**Expected behavior**
If the emails cannot be sent (e.g. cannot connect to Alkemio server, cannot connect to mail server) then the event on the queue should not be consumed (i.e. acknowledged)

**Comment by valentinyanakiev** [comment]
If at least one email is sent then we acknowledge.
