### ISSUE TITLE
UX: email notifications contents

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/notifications#56]
## Description

As a user I want to have well branded emails for platform notifications

## Acceptance criteria

- [ ] Refine the branding that is wrapped around all notification emails
- [ ] Optional: suggestions for updates / additional information to go into each of the notification emails. 

## Additional Context
Current emails look like below:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/d90f2643-9d2c-4a0c-b8aa-1e5b986a1ee3)

The html wrapper is shared across all emails, and is found here:
https://github.com/alkem-io/notifications/blob/develop/src/templates/_layouts/email-transactional.html

The various emails that are sent to users are in the following folder:
https://github.com/alkem-io/notifications/blob/develop/src/templates/

**Comment by Roseghost** [comment]
Adobe design: 
![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/babf6bc1-d694-4f7a-a877-b836568b47ea)

Bootstrap editor:  
![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/bfc717f0-f09a-4053-b625-4abc26f40c04)

Code: 
[Currently sorting storage cause you can't drop the file here]

Extra notes: 
- Team Alkemio has to go out of the javascript messages cause its double
- Clickable things (such as community name) needs to be stylized in the javascript file with color the alkemio dark-blue/green that is in the styleguide.

**Comment by techsmyth** [comment]
Actually quite important to get this through seeing how emails are coming through now:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/eff619a9-d066-4a29-9368-940cba7a08cd)

**Comment by Roseghost** [comment]
New Concept:  

![Email - optie 1.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/80ad7551-22b8-4e59-9c60-17f6e2bb6db1) 

Website link is double seeing theres links below 
![Email - optie 2.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/3650c24c-dd9c-43e7-9afc-04bb638b9351)

**Comment by Enderedne** [comment]
We should probably leave in only the Notification Settings + Website + Alkemio Hub in the footer. And also drop the twitter link.

**Comment by techsmyth** [comment]
Actually this needs to be thought through more as the current email composition has the footer as generic across environments. This is an issue as the notification settings and Alkemio Hub links would be specific per environment. 

This information is available when creating the email but not in the footer. It may need some additional work to get this footer configurable per environment. 

This needs a quick chat... @valentinyanakiev  @Enderedne
