### ISSUE TITLE
Make notifme multiProvider strategy configurable

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/notifications#58]
## Description

As a QA I want to be able to test notifications.

## Acceptance criteria

- [ ] Different multiProvider strategies can be configured via notifications.yml (roundrobin|no-fallback|fallback)

## Additional Context
The context is that at the moment if the SMTP server is down we have a hardcoded fallback to the console. The notification message will be directed to the console, the message will be acknowledged, and the recipients won't receive anything when the connection to the SMTP server is restored.

**Comment by techsmyth** [comment]
Clearly what we want to avoid in this situation is that the message gets acknowledged. Is it possible to adjust to throw an exception and then later make the strategy configurable?
