### ISSUE TITLE
BUG: When global admin is member of Hub community, receives challenge updates twice

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/notifications#65]
**Describe the bug**
When global admin is member of Hub community, receives challenge updates twice

**To Reproduce**

1. Go to https://dev.alkem.io/admin/hubs/un-sdgs/challenges/food/community/updates
2. Authenticate with ecoverse.member@alkem.io (it is challenge admin for the challenge)
3. Make sure the global admin is member of the parent hub of the challenge and have the configuration for community updates enabled
4. ecoverse.member@alkem.io makes challenge community update
5. Global admin receives email twice
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/e0fa5671-aece-48f2-9b4d-3ea8cdf5a342)

**Expected behavior**
Global admin receives only ones community update email.

**Comment by valentinyanakiev** [comment]
Compare the HTLM, the headers in the templates are the same. The body templates are the following:
member: 
```
 Hi {{recipient.firstname}},<br><br>

          A new discussion was created by {{createdBy.firstname} on your community <a href="{{community.url}}">{{community.name}}</a>: {{discussion.title}}<br><br>

          Sincerely yours,
          Team Alkemio
```

admin:
```
          Hi {{recipient.firstname}},<br><br>

          A new discussion was created by {{createdBy.firstname}} on <a href="{{community.url}}">{{community.name}}</a>: {{discussion.title}}<br><br>

          Sincerely yours,
          Team Alkemio
```
