### ISSUE TITLE
BUG: The URL returned in the templates are incorrect

### ISSUE THREAD

**Issue by Comoque1** [alkem-io/notifications#70]
**Describe the bug**

**To Reproduce**

1. Go to https://acc.alkem.io/admin/hubs/ole1/challenges/ole11/community/updates
2. Authenticate with user that have preferences to get mails from updates for the particular challenge community
3. Send an update - email is received, but the URL in the email is: `https://acc.alkem.io/ole1/ole11`

**Expected behavior**
The correct URL should be: 
#### For community updates
- [ ] for hub update: `https://acc.alkem.io/ole1/community/`
- [ ] for challenge update: `https://acc.alkem.io/ole1/challenges/ole11/community`
- [ ] for opportunity update: `https://acc.alkem.io/ole1/challenges/ole11/opportunitie/ole111/community`

#### For community discussions
- [ ] for hub discussion: `https://acc.alkem.io/ole1/community/discussions/1ad40cd4-67f1-425d-80e9-a558ec4c4f78`
- [ ] for challenge discussion: `https://acc.alkem.io/ole1/challenges/ole11/community/discussions/ec83dd0f-6f59-4594-aa31-77727b575a11`

**Additional context**
The same behavior is experienced of Discussions as well

**Comment by Comoque1** [comment]
Tested on Dev. 
With the current fix, the user link is pointing to the entity dashboard (i.e. https://acc.alkem.io/hubNameId/, https://acc.alkem.io/hubNameId/challenges/challengeNameId/, etc)
In the expected behavior it is stated to point to the entity corresponding community or discussion.
@techsmyth, if you approve the current behavior, we can close it?

**Comment by techsmyth** [comment]
It is fine that it points to the dashboard, thanks for checking...it can be closed
