### ISSUE TITLE
Emails moved to Azure; sent from notifications@alkem.io

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/notifications#79]
## Description

As an admin I want that notification emails come from a specific email address

## Acceptance criteria
- [ ] Notifications moved from AWS to Azure
- [ ] Notification emails to be sent from notifications@alkem.io (default)

Nice to have:
- [ ] Sending email address to be configurable

**Comment by valentinyanakiev** [comment]
The notifications service already sends emails from that address and it is configurable.
@techsmyth  @renehonig is there an smtp mail service created on Azure? If yes, I need credentials, If no - I suggest we defer that story.

**Comment by techsmyth** [comment]
@valentinyanakiev yes the service is already setup on Azure. I cannot give the details, but suggest you directly send Rene a message so he can send you pointers...

**Comment by Comoque1** [comment]
Tested with the following types of notifications:
- kratos service: user verification / signup
- notification service: create discussion / reply in a thread/ mention user
