### ISSUE TITLE
BUG: Email address "not accessible"

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/notifications#80]
**Describe the bug**
Just received a notification about a new user signing up on production, email as below:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/673c1605-4774-4ed1-b4d4-b55b5ef5fbda)

Note the email address is "not accessible" - this needs to be investigated as something may be wrong. 

**To Reproduce**

**Expected behavior**
Email address to be visible in the notification email.

**Comment by Comoque1** [comment]
The user receives correct email
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/ccee6514-0715-40d0-947a-f66568b05756)
After clicking on the link for verification, the second email also looks OK
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/bdc5d7f4-00a0-43dc-9fe6-a5e814a782b3)

**Comment by Comoque1** [comment]
Look OK on DEV env.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/35888c00-2448-4d30-8ff9-26eb19485698)
