### ISSUE TITLE
UX: Switch to using new banner in email notifications

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/notifications#93]
## Description

As a user I want a consistent interaction with the platform

## Acceptance criteria

- [ ] Emails sent from notifications service to use the new banner as seen on the hub home page

## Additional Context
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/554ff52e-90ea-4636-96b5-121b2535049d)

**Comment by KayleeS96** [comment]
Rose has sent a pull request for the updated image

**Comment by KayleeS96** [comment]
Visual of the email template with the new banner implemented

![image.png](https://images.zenhubusercontent.com/612cb1848a783db262f19451/06aea584-7cf5-4d13-b716-9dc785abc5aa)

**Comment by techsmyth** [comment]
@valentinyanakiev can you please generate a sample email with this footer?

**Comment by valentinyanakiev** [comment]
![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/bfb46ca2-5d4d-4458-8e89-af0048b9fb30)
